namespace aadog.PInvoke.LibGum.Enums;

public enum GumExceptionType
{
    GUM_EXCEPTION_ABORT = 1,
    GUM_EXCEPTION_ACCESS_VIOLATION,
    GUM_EXCEPTION_GUARD_PAGE,
    GUM_EXCEPTION_ILLEGAL_INSTRUCTION,
    GUM_EXCEPTION_STACK_OVERFLOW,
    GUM_EXCEPTION_ARITHMETIC,
    GUM_EXCEPTION_BREAKPOINT,
    GUM_EXCEPTION_SINGLE_STEP,
    GUM_EXCEPTION_SYSTEM
}