name: nuget push

on:
  workflow_dispatch:
    inputs:
      FRIDA_VERSION:
        description: 'nuget version'
        required: true
        default: '1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release -p:Version=${{ github.event.inputs.FRIDA_VERSION }}
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: nuget push
      run: dotnet nuget push './${{ github.event.repository.name }}/bin/Release/${{ github.event.repository.name }}.${{ github.event.inputs.FRIDA_VERSION }}.nupkg' --api-key ${{ secrets.NUGETAPIKEY }} --source https://api.nuget.org/v3/index.json